### ISSUE TITLE
Custom Fields, Relationships ... 

### ISSUE THREAD

**Issue by ArneNostitz** [ntawileh/obsidian-google-lookup#20]
Hi, first: this plugin is amazing ... besides the very complicated google setup :-)

is there a way to access more than the few fields you provide at the moment? i have an extensive list of Projects and related names connected to my contacts, notes etc and i would love to import this as well when creating a new contact .... maybe just a "dump" of all the info that is attached to a contact? 

thanks - arne

**Comment by ntawileh** [comment]
thanks for the feedback. any particular fields in contacts you are looking for?

**Comment by ArneNostitz** [comment]
i used "related names" a lot (for projects, referrals, locations, events ...) and notes.
also address and social web links would be great to translate over

as i am now building a more comprehensive database in obsidian i´d like to convert the whole info i have on these contacts over to further enhance these links. 

for example: i have used the related name like this:
John Smith
(related name key) Project: (related name value) Project X (Crew: Director)

Dane Jane
Projekt: Project X (Cast: Rolename)
met at: Oscars 2020, Reception

Jane Downs
Project: Project Y (Crew: Producer)
Referred by: John Smith



this was a way of not overusing tags or groups and be able to extend the information stored. also it was universal between google/apple/other apps ... without loosing any of these infos. they are also usable in the phones app and this info is searchable. 

but as i am building a CRM inside of Obsidian and a more detailed linkage could be great in this ... also using the dataview to filter through stuff ... its really amazing what this is capable of ...

anyway - if its easy to modify and add these it would be great!
----
also any way of configuring the way multiple phone numbers/emails are added (in a list for example)?

thanks so much for the fast response!

**Comment by ArneNostitz** [comment]
this is awesome! complete json is now available - thanks
