### ISSUE TITLE
Cannot See the commands in the Command Expolorer

### ISSUE THREAD

**Issue by vkbytes** [ntawileh/obsidian-google-lookup#24]
I installed the plugin and configured it according to the docs, 
1. Created a project
2. Created an external app
3. Added the information to the plugin
4. Authenticated to a google account. 

But when I try to see the commands in the expolorer, I don't see them and the hotkeys also don't work. 
I am on Obsidian 1.03.

**Comment by ntawileh** [comment]
not sure what hotkeys you are referring to.  the commands will be visible if both of those conditions are satisfied:

1. you must have configured the google account in settings.  client_id + client_secret should be set
2. you must be active in a markdown view. i.e. have a note already open and your focus/cursor should be in the note.  if your focus is elsewhere (for example in a folder), the command won't show

**Comment by vkbytes** [comment]
@ntawileh Thank you for the info.. Such a trivial problem, I was in a folder and in reading view and thats probably why it was not showing up.
