### ISSUE TITLE
Seeing Unknown for Contacts

### ISSUE THREAD

**Issue by vkbytes** [ntawileh/obsidian-google-lookup#25]
I have an issues where the first and the last name does not appear in the search and there by not creating the file with the desired name. 
![CleanShot 2022-11-12 at 16 20 26](https://user-images.githubusercontent.com/79217316/201470788-af7b4189-86a6-4f2d-b0f5-fe415443a393.png)
It does not happen for my user id though, I configured the right API access as well. Iam using this for our work domain 
Any idea why that would be the case.

**Comment by ntawileh** [comment]
I've seen this before.  I suspect it is the [External Directory Sharing](https://apps.google.com/supportwidget/articlehome?article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F6343701&product_context=6343701&product_name=UnuFlow&trigger_context=a) domain setting which would limit fields that are accessible via the API.
  
I don't know if you are an admin on your domain or if you're able to validate that.

**Comment by drye** [comment]
I have the same problem. This is the setting:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/199121/211806007-c845d9b3-bc74-4800-bc6d-8ec08b70eb2c.png">

Should the first option be selected for this to work instead?

**Comment by ntawileh** [comment]
I believe so.  If you are able to try it to confirm, that would be great.  Note that changes like this on the google side might take a while to take effect, so you might have to give it some time before trying.

**Comment by drye** [comment]
Hm, looks like this made it worse. Directory doesn't yield any results and in the obsidian log this is what I now see: 

```
unable to query directory: The G Suite domain admin has disabled external directory sharing. See more details at https://support.google.com/a/answer/6343701
```

**Comment by drye** [comment]
Update: waiting didn't help. WIth the `Public data and authenticated user basic profile fields` no directory results are returned at all. ☹️

**Comment by ntawileh** [comment]
bummer :/ thanks for checking.  it has to be some google setting; i'll dig around some more and see if i can figure it out

**Comment by ntawileh** [comment]
I believe this could be related to https://issuetracker.google.com/issues/196235775?pli=1

**Comment by ntawileh** [comment]
it seems google finally fixed this according to the status here: https://issuetracker.google.com/issues/196235775

hopefully this resolved your issue
