### ISSUE TITLE
News fields: middle name, contact URL

### ISSUE THREAD

**Issue by agnoldo** [ntawileh/obsidian-google-lookup#3]
Hello @ntawileh , first of all, thank you so much for this plugin! Amazing job. The possibilities are endless: imagine creating a contact note for every Google Contact and referring to these notes in other notes? And then using Dataview or Backlinks to list all interactions? Really great!!!

In order to support this vision even better, I'd like to suggest that other fields from contacts become available. I know the list of fields is huge, but at least "middle name" and "contact URL" would make a lot of difference. Middle name is common in many latin countries, where we don't use only first and last. And the contact URL (https://contacts.google.com/person/c15, for example)  would enable us to open the contact and see the rest of information (so it's not necessary to import everything).

Thanks in advance and congratulations again!

**Comment by ntawileh** [comment]
nice, thanks for the feedback. really like the URL idea

**Comment by agnoldo** [comment]
Thank you very much, @ntawileh ! I'll gladly use it as soon as it arrives in Obsidian...

**Comment by agnoldo** [comment]
Amazing! Thank you very much! Already tested here and it worked beautifully!!!

**Comment by agnoldo** [comment]
Dear @ntawileh , just a small comment: when the middlename is empty, it's coming as "unknown". If it's not too difficult, it would be better to come empty, as "".

BTW, thank you very much. It's already very good!

**Comment by ntawileh** [comment]
yeah I guess doesn't hurt to default middle to an empty string as long as some other name fields contain something.  I'll adjust that in the next release

**Comment by agnoldo** [comment]
Yes, totally agreed. Thank you very much!
