### ISSUE TITLE
Account will not connect on Desktop

### ISSUE THREAD

**Issue by disco-lemonade** [ntawileh/obsidian-google-lookup#33]
Hello, I have tried creating a Google API (OAuth) -> adding my client ID and Key to the plugin.  I click ad account and follow through googles permission screen.  I get the message:  "OK - You can close this tab and go back to Obsidian!"
However, the account does not add to the plugin.  

Am I missing a step?

**Comment by ntawileh** [comment]
what happens in Obsidian when you get the 'OK...' message in the browser?  Is the add account dialog box (that has the `click here to authenticate`) still open or has that closed?
