### ISSUE TITLE
Asks to reconnect to accounts every day or every other day

### ISSUE THREAD

**Issue by jmburges** [ntawileh/obsidian-google-lookup#35]
Hello and thank you for this plugin!

I must be doing something wrong. The plugin asks to reauthenticate with my google account almost every day if not every other day. Is it not storing a refresh token of some sort? Did I configure it incorrectly?

Thank you!

**Comment by jmburges** [comment]
Wow thanks for the quick response!

1) My account is a normal @gmail.com account. 
2) I created an account in testing mode.

Are both of those correct?

**Comment by ntawileh** [comment]
If it's a test user, you should get 7 days of validity (which is what I also use), according to [Google's docs](https://support.google.com/cloud/answer/10311615#zippy=%2Ctesting:~:text=Authorizations%20by%20a%20test%20user%20will%20expire%20seven%20days%20from%20the%20time%20of%20consent.%20If%20your%20OAuth%20client%20requests%20an%20offline%20access%20type%20and%20receives%20a%20refresh%20token%2C%20that%20token%20will%20also%20expire.).

I cannot think of a reason unfortunately why yours would expire in one day.  The only other thing I can think of is if you have too many applications using your gmail.com account, then that might be a factor (I think Google will support up to 50 refresh tokens per account)
