### ISSUE TITLE
Struggling with moving Contact note to folder

### ISSUE THREAD

**Issue by RCheesley** [ntawileh/obsidian-google-lookup#36]
Hi folks,

Thanks for the great plugin, which is working amazingly but for one part!

I want to move the people note into a folder called 'People' - top level folder in my vault.

I've got it set as follows in the plugin settings:

![screenshot-nimbusweb me-2023 04 29-13_24_54](https://user-images.githubusercontent.com/2930593/235302427-ec3f08b5-4ad5-4352-9f2e-b53f3aeff7dc.png)

It's picking up the template location fine.

The information is included when I call the contact details command, but it fails to move the note into the People folder, saying it doesn't exist.

I've tried various formats but I'm not getting anywhere fast. Is there something I am missing here? It's not obvious from the docs if there needs to be anything other than the path relative to the root, so maybe it's a bug somewhere?

**Comment by ntawileh** [comment]
It should just be the path relative to the root.  I actually use it with a top-level folder called `people` as well.

  * what OS are you running on?
  * do you have the same problem with the default contact template?  if not, and this only happens with your template, can you share your contact template content here?
  * can you share the contents of your plugin preferences?  this would be the contents of `.obsidian/plugins/obsidian-google-lookup/data.json` - please make sure you exclude/remove the google client params (client_id and client_secret)

**Comment by RCheesley** [comment]
I think the issue was that I had updated my folder structure and the template couldn't find the new location! It's working now so I'll close the issue.
