### ISSUE TITLE
#person/{{source}} formatting

### ISSUE THREAD

**Issue by srustamo** [ntawileh/obsidian-google-lookup#38]
My email returned by '{{source}}' has a dot in the name as in 'sh.ru@gmail.com'.

The '#person/{{source}}' returns '#sh' only as a tag. 
'.ru@gmail.com' is returned as an email address, clickable as 'send email to' link.

Is there a way to escape the '.' in the email name?

**Comment by ntawileh** [comment]
I would probably just make a new template that doesn't have `#person/{{source}}` in it.  You can still copy the default template from [here](https://ntawileh.github.io/obsidian-google-lookup/person/#template-fields) and just customize/remove that field.

alternatively, if you really want to keep that and escape the dot, you can use the [Templater](https://ntawileh.github.io/obsidian-google-lookup/person/#using-templater) along with the `{{json}}` field and manipulate source however you like.
