### ISSUE TITLE
Docs: Template Fields and Google People API

### ISSUE THREAD

**Issue by srustamo** [ntawileh/obsidian-google-lookup#39]
Is the list of Template Fields taken from the Google People API? Can you point me to the Google People API docs?

**Comment by ntawileh** [comment]
> Is the list of Template Fields taken from the Google People API?

not quite.  there is a relationship for sure, but it isn't 1:1 - as in, if you find some other field in the Google API and you just plug it in the template, it won't work.  The fields available for the plugin are what's listed in the plugin docs.

> Can you poing me to the Google People API docs?

https://developers.google.com/people/api/rest/v1/people#Person

**Comment by srustamo** [comment]
Are there any plans to include more API fields (e.g. photos)?

**Comment by ntawileh** [comment]
haven't thought about photos before, but you're welcome to create an issue here requesting that.  Would be great if you described your use case in there for the fields you are asking for

**Comment by srustamo** [comment]
I'm thinking of using Obsidian as a mini-CRM. I meet many people, most of them once or twice, so it is useful to put a face behind their record to quickly refresh my memory if I plan to meet someone again after a long while. I'm not sure how Google stores the pictures and if the API allows a file download or a link to the photo. Either way is OK. 

Another API field which is missing from the template is the 'label' field. Google allows to label contacts to group them. I use it to quite often, not sure if others do, so would be great to the related field in the template, too.

Finally, the 'notes' field in the API is mapped to 'bio' in the template. It would be great to bi-directionally update only this field from the data in Obsidian. But that's probably a whole different project.

**Comment by ntawileh** [comment]
created issue for contact photo; i think that should be fairly straightforward.  the api returns them in a URL, and they could be linked into the template.  you can follow that other issue if you like

https://github.com/ntawileh/obsidian-google-lookup/issues/40

> Another API field which is missing from the template is the 'label' field. Google allows to label contacts to group them. I use it quite often, not sure if others do, but would be great to have a related field in the template, too.

I think that is a feature of the google contact app and not something that is made available to third parties.  I couldn't find the field for it in the API, but if you do, go ahead and open an issue for it if you like

> Finally, the 'notes' field in the API is mapped to 'bio' in the template. It would be great to bi-directionally update this field from the data in Obsidian (or perhaps all fields). But that's probably a whole different project.

maybe at some point in the future, but for now one of the principles I'm trying to stick to is read-only from Google.  Starting to support updates would be a very different project as you mentioned.

thanks for all the feedback!
