### ISSUE TITLE
Format for the name of the contact

### ISSUE THREAD

**Issue by agnoldo** [ntawileh/obsidian-google-lookup#4]
Hello @ntawileh , thanks for the amazing work. Another idea: to enable users to define the format of the name of the contact (when we choose the option "Rename and move person file", which is great, BTW). Since the name is very important in Obsidian (I know I can use aliases but name is easier), it would help us to organize our 1,000 contacts in Contacts folder.

Thanks again!

**Comment by agnoldo** [comment]
Dear @ntawileh , thanks for implementing the other suggestion. For this one, if you think it is easier to use a field in YAML (FrontMatter), for me it's also a good choice. 

Bye!

**Comment by ntawileh** [comment]
> if you think it is easier to use a field in YAML (FrontMatter), for me it's also a good choice.

i just went with a setting for now.  might be cool to have some template properties type tags in yaml in the future if there's more options that need to go in

**Comment by agnoldo** [comment]
Amazing! Thank you very much! Already tested here and it worked beautifully!!!
