### ISSUE TITLE
Unable to Activate Google Lookup

### ISSUE THREAD

**Issue by kennygokh** [ntawileh/obsidian-google-lookup#44]
Hi, it seems like latest version of Obsidian v1.6.3 break this plug in. I am not able to find the plug in in command palette. However, it is found in Hotkeys settings. I assigned a hotkey to try to activate the plug in but no success. Nothing happen, no error. Please help to check.

**Comment by ntawileh** [comment]
the plugin commands are only visible if you are active inside a notes window.  i.e. if you hit a key on the keyboard, you see it in the note.
if your focus is in the folder view, for example, or any other pane in Obsidian, then the commands do not show up in the palette.

can you confirm you are in a notes view?  I'm on 1.6.3 btw and haven't noticed any changes or issues myself

**Comment by kennygokh** [comment]
> the plugin commands are only visible if you are active inside a notes window. i.e. if you hit a key on the keyboard, you see it in the note. if your focus is in the folder view, for example, or any other pane in Obsidian, then the commands do not show up in the palette.
> 
> can you confirm you are in a notes view? I'm on 1.6.3 btw and haven't noticed any changes or issues myself

Thanks. It works now.
