### ISSUE TITLE
Adding second account: work and non-work

### ISSUE THREAD

**Issue by arcegabriel** [ntawileh/obsidian-google-lookup#46]
I have set the plugin to work with my work Google Workspace. Works like a charm
I assume to add a personal account I would need to follow the same process, however I don't see a place to put another set of Client ID and Client Secret?
How would I do that?

**Comment by ntawileh** [comment]
you don't really need another client id/secret.  you can just use the same ones.  just add another account directly.

**Comment by arcegabriel** [comment]
Hi, I get this error which is what I expect
Access blocked: Obsidian Google Contacts and Calendar has not completed the Google verification process
I am assuming the plugin is using API calls, I don't understand the project on my work google account can make api calls work on personal google account. In fact I would think this would be a big issue??

**Comment by ntawileh** [comment]
there is some instructions and background here https://ntawileh.github.io/obsidian-google-lookup/google-setup/ - this is the summary though:

- the google client id and secret are not tied to any google account.  all those do is identify the APPLICATION being used, NOT the USER using it.  For example, any site you have visited which allows you to "Sign in with Google" has a client id+secret stored somewhere by the developer of the app.
- the user and access to user/account information comes into play when you sign in (the web-based Auth flow that tells you "So and so application wants access to your calendar - do you want to allow that?"

Now back to your issue, there are instructions on that same URL on how to set up the google client app.  If you are trying to publish it as an external app available to ANY user, Google will need to verify some things and that's the error you are getting.  Alternatively you can choose to not publish it, keep the app in "Testing" mode, and then you can add test users.  In this case, you could add your work account, personal account, anything else.  

Hope this helps

**Comment by arcegabriel** [comment]
Hi, Got it and now it is working
Sorry I obviously was confused at where the auth was. 
I am keeping it as "Testing " and assume it is all well. Thanks!
